### PR TITLE
Add Bulgarian langulage

### PR DESCRIPTION
**Pull request by ynedelchev**
Hi

I wrote a localization for Bulgarian Language for Phorum. 
Hope you include it in the official release.

Best Regards
Yordan Nedelchev

### CODE REVIEW

**Comment by ynedelchev** [comment]
You could actually see it working here: http://bgkalendar.com/forum/. That is using version 5.20 I believe.

**Comment by oricgn** [comment]
Hi Yordan,

please post your language file in our [Language Files Forum](http://www.phorum.org/phorum5/list.php?65).

The Phorum core only contains english language files.

Regards
Oliver

**Comment by oricgn** [comment]
P.S. Did you notice the [other Bulgarian language file](http://www.phorum.org/phorum5/read.php?65,140492)?

**Comment by ynedelchev** [comment]
Thanks Oliver

Will post it there.
Sadly, I never noticed there is already existing translation.

May I recommend you put a simple readme file in the language directory that redirects you to the correct place for translations.

Best Regards
Yordan

**Comment by oricgn** [comment]
Hi Yordan,

> Will post it there. Sadly, I never noticed there is already existing translation.

You can compare our two Bulgarian language files and post a improved version.

> May I recommend you put a simple readme file in the language directory that redirects you to the correct place for translations.

I put a reference into the English language file:
https://github.com/oricgn/phorum-core/commit/0ac74c6a0946577e578edb7d1342595660a19495

Regards
Oliver

**Pull request closed without merging**
